// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sirkelen.Shared.Migrations
{
    [DbContext(typeof(SirkelenContext))]
    [Migration("20241003161242_SeedingDataNew")]
    partial class SeedingDataNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4117473c-ec8a-4558-92a0-d4e81fd93979"),
                            IsAdmin = true,
                            JoinDate = new DateTime(2024, 10, 3, 18, 12, 42, 167, DateTimeKind.Local).AddTicks(5270),
                            Name = "Alex",
                            PasswordHash = "$2a$11$7BYgs2gUCqrhWus4S2kWo.itgGrBlsHPZFqqQBWbiwXiObEfMMQxm",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("13dd31fe-5f3b-4a5d-9a54-f7792258e343"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 18, 12, 42, 316, DateTimeKind.Local).AddTicks(8100),
                            Name = "Atle",
                            PasswordHash = "$2a$11$4dbrPjeuVTndNcit447J8OTXVHbR0RNqnUuMEZeE3EAlJxgTNSTmC",
                            Username = "atse02"
                        },
                        new
                        {
                            Id = new Guid("01425677-1175-4b86-b52e-76efaabb2757"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 18, 12, 42, 462, DateTimeKind.Local).AddTicks(7150),
                            Name = "Brage",
                            PasswordHash = "$2a$11$Sjito3vGqC/mqOHT6RI1jurQXTtyuqRgBXtF2WPSAyX6LITLOX4hi",
                            Username = "bragstern"
                        },
                        new
                        {
                            Id = new Guid("4e431693-feb8-4a5f-b3e8-78920e576bc6"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 18, 12, 42, 606, DateTimeKind.Local).AddTicks(8570),
                            Name = "Sander",
                            PasswordHash = "$2a$11$v2nyp3/luXeR/cuSDwrAl.3PRZrhm8RTKoam0RwNaadKAsA/k.t2W",
                            Username = "sandercool"
                        },
                        new
                        {
                            Id = new Guid("57b782cc-141b-4055-8ecd-9a48ee409709"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 18, 12, 42, 751, DateTimeKind.Local).AddTicks(670),
                            Name = "Vuong",
                            PasswordHash = "$2a$11$/2fOZnf4BgFkWsWvjZIueeekAxP/INdeJqj/V9VUoXdLaQQLt6ft2",
                            Username = "vuonguyen"
                        });
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightRecords");
                });

            modelBuilder.Entity("Messages", b =>
                {
                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("PersonalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("WeightRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("PersonalRecords");

                    b.Navigation("WeightRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
