// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sirkelen.Shared.Migrations
{
    [DbContext(typeof(SirkelenContext))]
    [Migration("20241003151821_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d54653cd-edcc-4431-bf2a-a1abcfb17d46"),
                            IsAdmin = true,
                            JoinDate = new DateTime(2024, 10, 3, 17, 18, 20, 310, DateTimeKind.Local).AddTicks(1670),
                            Name = "Alex",
                            PasswordHash = "$2a$11$1ykGNfNkLuTOTFVrkyIVFeoLJ8UlQ8WphAH9R9C6dJRnc51MksxiO",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("6a13a748-54dc-47fc-a9e2-67e234178c78"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 17, 18, 20, 452, DateTimeKind.Local).AddTicks(7020),
                            Name = "Atle",
                            PasswordHash = "$2a$11$V9EPvfQR9h6MGicKvi5y5OMkfhazbylC.MWgaSlRggZrdygXH3dki",
                            Username = "atse02"
                        },
                        new
                        {
                            Id = new Guid("116763b5-6ba5-4be4-8987-bbcbbc9c292f"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 17, 18, 20, 595, DateTimeKind.Local).AddTicks(2210),
                            Name = "Brage",
                            PasswordHash = "$2a$11$QbbW7MJN1S19Ths8VXzt1.0xNj4lZpkjR2G2Y02YnS3TBEmnI/kJS",
                            Username = "bragstern"
                        },
                        new
                        {
                            Id = new Guid("ee2490bd-79ad-4b11-98d5-560f0af6e711"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 17, 18, 20, 734, DateTimeKind.Local).AddTicks(6700),
                            Name = "Sander",
                            PasswordHash = "$2a$11$7fCp5qFF0Yvu/MLCA4bJMustakdueJ0w8titi5UGJbUTBSkpvHQeK",
                            Username = "sandercool"
                        },
                        new
                        {
                            Id = new Guid("50db4520-9156-4b85-8d12-2332391064f9"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 3, 17, 18, 20, 874, DateTimeKind.Local).AddTicks(3860),
                            Name = "Vuong",
                            PasswordHash = "$2a$11$1euBcOOJYPeuJZz33o5wi.oNDcvUvozu0RqY.VoDc1AEFWuuZjgmO",
                            Username = "vuonguyen"
                        });
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("FriendsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("FriendsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightRecords");
                });

            modelBuilder.Entity("Messages", b =>
                {
                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("PersonalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("WeightRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("PersonalRecords");

                    b.Navigation("WeightRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
