// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sirkelen.Shared.Migrations
{
    [DbContext(typeof(SirkelenContext))]
    partial class SirkelenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a12fa66c-0a51-44d9-af73-728b35596642"),
                            IsAdmin = true,
                            JoinDate = new DateTime(2024, 10, 4, 0, 31, 15, 733, DateTimeKind.Local).AddTicks(7650),
                            Name = "Alex",
                            PasswordHash = "$2a$11$zlttYoY/1Q6WJATLcgHADebaVx3O8ucX1aic9i4ruSgB9NlUqlsO2",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("2a352af4-ca16-47d1-ac9a-b69b4dbb5e0f"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 4, 0, 31, 15, 882, DateTimeKind.Local).AddTicks(590),
                            Name = "Atle",
                            PasswordHash = "$2a$11$l4Ib1xjuH9dSUxriV4sz3.PJTUVPPFGRt71Bv5G.IFY0F1GzN7vz2",
                            Username = "atse02"
                        },
                        new
                        {
                            Id = new Guid("ea02dde6-d7d8-41ec-8566-507a853a1b58"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 4, 0, 31, 16, 28, DateTimeKind.Local).AddTicks(8120),
                            Name = "Brage",
                            PasswordHash = "$2a$11$a2SUyLX5NXgF2V/qmJ1tzudMYlXWlVh0aE9XuZyhW9tZrSZpGsTMu",
                            Username = "bragstern"
                        },
                        new
                        {
                            Id = new Guid("56d877e4-316e-4b7d-a473-831c305c6e67"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 4, 0, 31, 16, 172, DateTimeKind.Local).AddTicks(8920),
                            Name = "Sander",
                            PasswordHash = "$2a$11$AXKCRYeo3stBDUgLYyHPUeJXDIFj/Pd1Vuuyoh9gk3i4EyuF4YZEy",
                            Username = "sandercool"
                        },
                        new
                        {
                            Id = new Guid("19d74b5a-b751-4662-9491-e9b0c77e5cc4"),
                            IsAdmin = false,
                            JoinDate = new DateTime(2024, 10, 4, 0, 31, 16, 317, DateTimeKind.Local).AddTicks(720),
                            Name = "Vuong",
                            PasswordHash = "$2a$11$qf7BhAkMVaW/rIplo3KAv.C3DTnAas6EdImzY27fuZsgDDq8TEwvS",
                            Username = "vuonguyen"
                        });
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeightRecords");
                });

            modelBuilder.Entity("Messages", b =>
                {
                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PersonalRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("PersonalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeightRecord", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("WeightRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("PersonalRecords");

                    b.Navigation("WeightRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
