<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <MauiAsset Include="ServiceAccount.json" />
  </ItemGroup>
  <ItemGroup>
    <None Update=" \ServiceAccount.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
</ItemGroup>



  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Firebase.Auth" Version="1.0.0" />
    <PackageReference Include="FirebaseDatabase.net" Version="4.2.0" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.8" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.91" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.1.1" />
  </ItemGroup>

</Project>
